[pytest]

# Ajoute la racine du projet au PYTHONPATH
# Permet les imports comme "from api.questions_api import QuestionsAPI"
pythonpath = .

# Ignore les warnings Python dans la sortie des tests
filterwarnings = ignore

# Options ajoutées automatiquement à chaque commande pytest
# Ralentit chaque action Playwright de 2 secondes
# Sauvegarde les résultats Allure dans le dossier reports/allure-results
addopts = --slowmo 2000 --alluredir=reports/allure-results

#tags personnalisés pour organiser les tests
markers =
    api: tests liés à l'API
    ui: tests liés à l'interface
    e2e: tests end-to-end